### PR TITLE
react minify fail error fix, using convertion of code into es2015

### PR DESCRIPTION
**Pull request by cybershivanka**

### CODE REVIEW

**Comment by tumerorkun** [comment]
Hi, thanks for pull request but you shouldn't convert src files. babel converts those files to lib folder and npm uses lib/index.js as main. i changed babelrc for es2015 conversion.

**Comment by cybershivanka** [comment]
Hi,

ah, its my bad. i'm kind of new to this thing and in a hurry to give a
working release of my app to some other developers. Sorry for the
inconvinience.
Anyway now what should i do ? update to the latest version will fix it ?

**Comment by tumerorkun** [comment]
yes, it is es5 now. you can clone "https://github.com/tumerorkun/react-leaflet-components-examples repo for react-leaflet" version 1 or "https://github.com/tumerorkun/react-leaflet-v2-tests" for react-leaflet version 2 and check it out the usage.

make sure you use babel + webpack or typescript or other tools to transpile code to es5 and don't forget the css-loader because this component has css imports in it. i'm going to write detailed readme asap.

**Comment by cybershivanka** [comment]
Thanks a lot.
I'm trying to enable checkbox on the group header, have u any built-in
functionality for this...

**Comment by tumerorkun** [comment]
Not yet but it will.

**Pull request closed without merging**
